# -*- coding: utf-8 -*-
"""insertion_sort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10lAZ8O5LyjDt9MB60wQm949bUOTrRzgf
"""

def insertion_sort(lista, i=1):
  if i == 1:
    print(lista) # Imprime la lista inicial
  elif i >= len(lista):
    return # Corta el proceso cuando se alcanza el último elemento

  pivote = lista[i] # Pivote = Elemento que hace la comparación
  j = i - 1 # J =  Elemento anterior para comparar

  while j >= 0 and lista[j] > pivote: # Tope para comparar al primer elem máximo
    lista[j + 1] = lista[j] # Se hace cambio de elementos
    j -= 1
  lista[j + 1] = pivote

  print(f"Paso {i}: {lista} Pivote actual: {pivote}")

  insertion_sort(lista, i + 1)  # Llamada recursiva

conjunto = [4, 9, 8, 3, 1, 0, 2, 0]

insertion_sort(conjunto)